server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6482141
    username: sql6482141
    password: ZR3SXdg6ht
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  file:
    path: D:\Work\capstone\log
  level:
    com:
      edu:
        capstone:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG