spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
  jpa:    hibernate:      ddl-auto: create
    show-sql: true    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    path: D:\Work\capstone\log
  level:
    com:
      edu:
        capstone:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG