server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_587495811eb0d5e?
    username: b0c3deb2fbf425
    password: 0b8c0fb9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  file:
    path: D:\Work\capstone\log
  level:
    com:
      edu:
        capstone:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG