spring:
  datasource:
    url: jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6480568
    username: sql6480568
    password: IE7pDQar4V
  jpa:    hibernate:      ddl-auto: update
    show-sql: true    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  file:
    path: D:\Work\capstone\log
  level:
    com:
      edu:
        capstone:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG